# syntax=docker/dockerfile:1

# Stage 1: Build the application using the SDK image
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

ENV APP_NAME=SimpleApi

# Copy csproj and restore any dependencies (via NuGet)
COPY ${APP_NAME}/*.csproj ./
Run echo $APP_NAME
RUN ls -la
RUN dotnet restore

# Copy the project files and build the release
COPY . ./
WORKDIR ./${APP_NAME}
RUN dotnet publish -c Release -o /app/out

# Stage 2: Build the runtime image using the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "SimpleApi.dll"]
