apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "SampleApp.fullname" . }}
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    {{ include "SampleApp.labels" . | indent 4 }}
spec:
  replicas: {{ include "SampleApp.replicaCount" . }}
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "SampleApp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "SampleApp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        # prometheus.io/scrape: "true"
        # prometheus.io/path: "/metrics"
        # prometheus.io/port: {{ .Values.container.probePort | quote }}
    spec:
      {{- with .Values.image.pullSecrets }}
        imagePullSecrets:
          {{- toYaml . | indent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ SampleApp.image}}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: app
              containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /ready
          #     port: {{ .Values.container.probePort}}    
          #   initialDelaySeconds: 10
          #   periodSeconds: 10 
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /live
          #     port: {{ .Values.container.probePort}}    
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          env:
            - name: RepoCommitId
              value: {{ .Values.repoCommitId }}

