name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dotnet_build_and_test:
    uses: owerchainger/infrastructure-shared/.github/workflows/dotnet_build.yml@main
    with: 
      dotnet_version: 6.0.x
  docker_build_and_test:
    uses: ./.github/workflows/docker_build.yml
    with:
      file: ./DevOps/dockerfile
      context: .
      push: true
      application: cicd-test
