name: main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_test:
    uses: ./.github/workflows/dotnet_test.yml
    with: 
      dotnet_version: 6.0.x
      
