name: Play with vars and envs

on:
  push:
  workflow_dispatch:

env:
  DAY_OF_WEEK: Monday

jobs:
  display:
    runs-on: ubuntu-latest
    steps:
      - name: show the value
        run: echo "${{github.ref == format('refs/heads/{0}', 'master')}} /n ${{github.ref}}"
      - name: Set the value
        run: |
          echo "action_state=yellow" >> "$GITHUB_ENV"
      - name: "show all available vars"
        run: env
      - name: "use var out of GITHUB_ENV file"
        run: echo "$DAY_OF_WEEK"
      - name: "use config value from vars context"
        run: echo "${{vars.TEST_CONFIGURATION}}"
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Setup env on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Override DAY_OF_WEEK on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
          DAY_OF_WEEK: Tuesday
      - name: "Don't setup env on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
  greeting_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: "Setup env on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: "Override DAY_OF_WEEK on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
          DAY_OF_WEEK: Tuesday
      - name: "Don't setup env on step level"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
