name: choice environments from var

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: boolean

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.environments.outputs.output}}
    steps:
      - name: Environments to be run against
        run: |
          if "${{ toJson(inputs.flag) }}" ; then
            echo '${{ vars.eevs }}' > environments.json
          else
            echo '${{ vars.QA_ENVS }}' > environments.json
          fi
      - name: Set  environment output
        id: environments
        run: echo "output=$(cat environments.json)" >> $GITHUB_OUTPUT
  test:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.init.outputs.environments) }}
    steps:
      - run: echo "${{matrix.env}}"
