name: choice environments from var

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ inputs.flag && ["test", "test2"] || ["o", "o2"] }} 
    steps:
      - run: echo "${{matrix.env}}"
