name: test dispatch
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: false
        type: choice
        options: echo ${{ fromJson(vars.envs) }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo $ {{inputs.environment}}
        echo ${{ fromJson(vars.envs) }}
