name: choice environments from var

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: boolean

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.environments.outputs.output}}
      empty: ${{steps.empty.outputs.output}}
    steps:
      - name: Environments to be run against
        run: |
          if "${{ toJson(inputs.flag) }}" ; then
            echo '${{ vars.eevs }}' > environments.json
          else
            echo '${{ vars.QA_ENVS }}' > environments.json
          fi
      - run: cat environments.json
      - name: Install jq
        run: sudo apt-get install -y jq
      - name: Set  environment output
        id: environments
        run: echo "output=$(cat environments.json)" >> $GITHUB_OUTPUT
      - name: Set environment empty 
        id: empty
        run: |
          ARRAY_LENGTH=$(cat environments.json | jq length)
          if [ "$ARRAY_LENGTH" -eq 0 ]; then
            echo "output=true" >> $GITHUB_OUTPUT
          else
            echo "output=false" >> $GITHUB_OUTPUT
          fi
      - run: echo $GITHUB_OUTPUT
  test:
    needs: [init]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.init.outputs.environments) }}
    steps:
      - run: echo "${{matrix.env}}"
      - run: echo "${{needs.init.outputs.empty}}"
