name: test dispatch
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: false
        type: choice
        options: 
          ${{ fromJson('["asd", "asdfsad"]') }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: test
      run: |
        echo $ {{inputs.environment}}
        echo  ${{ fromJson('["asd", "asdfsad"]') }}
