name: choice environments from var

on:
  workflow_dispatch:
    inputs:
      flag:
        required: true
        type: boolean

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.environments.outputs.envs}}
      empty: ${{steps.environments.outputs.is_empty}}
    steps:
      - name: Environments to be run against
        id: environments
        run: |
          if "${{ toJson(inputs.flag) }}" ; then
            echo '${{ vars.eevs }}' > environments.json
          else
            echo '${{ vars.QA_ENVS }}' > environments.json
          fi
          
          echo "envs=$(cat environments.json)" >> $GITHUB_OUTPUT
          
          ARRAY_LENGTH=$(cat environments.json | jq length)
          if [ "$ARRAY_LENGTH" -eq 0 ]; then
            echo "is_empty=true" >> $GITHUB_OUTPUT
          else
            echo "is_empty=false" >> $GITHUB_OUTPUT
          fi
      - run: cat environments.json
      - run: echo ${{steps.environments.outputs.is_empty}}
  test:
    needs: [init]
    if: needs.init.outputs.empty != 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ${{ fromJson(needs.init.outputs.environments) }}
    steps:
      - run: echo "${{matrix.env}}"
      - run: echo "${{needs.init.outputs.empty}}"
